local WritingChecklist=require(script.Parent.WritingChecklist)
local Definitions={PlayerTurnsEach=3,TurnSeconds=45,MaxArgumentBytes=500}
Definitions.Unlocks=table.freeze({{Points=0,Id="starter-chair",Label="Starter Chair",Kind="chair"},{Points=30,Id="blue-chair",Label="Blue Chair",Kind="chair"},{Points=60,Id="clear-thinker",Label="Clear Thinker title",Kind="title"},{Points=100,Id="gold-chair",Label="Gold Chair",Kind="chair"}})
local prompts={Opening="State your assigned position and give one reason.",Rebuttal="Respond to the other side and identify a trade-off or weakness.",Closing="Summarize your case and give one concrete example or consequence."}
local function topic(id,character,question,proposition,forPosition,againstPosition,forHint,againstHint)
 return {Id=id,Character=character,Proposition=proposition,Topic=question,Sides={Affirmative={Id="affirmative",Label="FOR",Position=forPosition,OpeningPrompt=forHint},Negative={Id="negative",Label="AGAINST",Position=againstPosition,OpeningPrompt=againstHint}},ScriptedOpening="Rivet, Pip and Moss assigned one player to each side. The scripted panel tracks visible writing features only; it does not judge which argument is true or stronger.",TurnPrompts=prompts}
end
Definitions.Topics=table.freeze({
 topic("hints","Rivet","Should hints be optional in building games?","Building games should make hints optional.","Hints should be available but optional.","Games should use one consistent hint system.","Explain how choice helps different players.","Explain how consistency improves the experience."),
 topic("pieces","Pip","Should build challenges limit the number of pieces?","Build challenges should limit pieces.","Challenges should use a clear piece limit.","Challenges should allow unrestricted piece counts.","Explain how limits improve creativity or fairness.","Explain how freedom improves creativity or access."),
 topic("scores","Moss","Should team games show individual contribution scores publicly?","Team games should show public contribution scores.","Contribution scores should be public.","Contribution details should remain private.","Explain how visibility helps teams.","Explain how privacy helps teams."),
 topic("homework","Rivet","Should schools replace some homework with projects?","Schools should replace some homework with projects.","More learning should happen through projects.","Regular homework should remain the main practice format.","Explain what projects teach better.","Explain what regular homework practices better."),
 topic("school_start","Pip","Should the school day start later?","Schools should begin later in the morning.","A later start would help students.","The current start time should stay.","Explain a benefit of a later morning.","Explain a cost of moving the schedule."),
 topic("uniforms","Moss","Should schools require uniforms?","Schools should require uniforms.","Uniforms improve the school experience.","Students should choose their own clothes.","Explain how uniforms help students.","Explain why clothing choice matters."),
 topic("phones","Rivet","Should phones be banned during class?","Phones should be banned during lessons.","Classrooms should be phone-free.","Teachers should allow responsible phone use.","Explain how a ban helps learning.","Explain a useful classroom role for phones."),
 topic("four_day_week","Pip","Should workplaces use a four-day week?","Workplaces should adopt a four-day week.","Four working days can improve results.","Five working days remain more practical.","Explain how fewer days could work.","Explain what five days protects."),
 topic("remote_work","Moss","Should employees choose where they work?","Employees should choose remote or office work.","Workers should choose their location.","Employers should set shared workplace rules.","Explain how choice improves work.","Explain why a shared policy helps teams."),
 topic("public_transport","Rivet","Should city public transport be free?","Cities should make public transport free.","Riders should not pay fares.","Fares should fund the service.","Explain a citywide benefit of free travel.","Explain why fares are useful or fair."),
 topic("cars_center","Pip","Should city centers restrict private cars?","City centers should restrict private cars.","Fewer private cars would improve city centers.","Drivers should keep access to city centers.","Explain what a restriction improves.","Explain who still needs car access."),
 topic("plastic","Moss","Should single-use plastic be banned?","Single-use plastic should be banned.","A ban is worth the transition.","Better recycling is preferable to a ban.","Explain an environmental benefit.","Explain why alternatives or recycling work better."),
 topic("space","Rivet","Should governments spend more on space exploration?","Governments should increase space funding.","Space exploration deserves more public money.","Public money has more urgent uses on Earth.","Explain a practical benefit of space research.","Explain which Earth need should come first."),
 topic("zoos","Pip","Should modern zoos continue to exist?","Modern zoos should continue operating.","Well-run zoos help conservation and education.","Wild animals should not be kept in zoos.","Explain a conservation or education benefit.","Explain the welfare cost of captivity."),
 topic("ai_school","Moss","Should students be allowed to use AI for schoolwork?","Students should be allowed to use AI tools.","AI can support learning when disclosed.","AI use should be prohibited for school assignments.","Explain a responsible learning use.","Explain a risk to learning or fairness."),
 topic("robots","Rivet","Should robots do dangerous jobs instead of people?","Robots should replace people in dangerous jobs.","Automation should take the riskiest work.","People should remain central even in dangerous work.","Explain how automation reduces harm.","Explain what human control protects."),
 topic("games_art","Pip","Should video games be treated as art?","Video games should be recognized as art.","Games can express ideas as art does.","Games are primarily entertainment products.","Give an example of artistic expression in games.","Explain what separates art from entertainment."),
 topic("esports","Moss","Should esports count as sports?","Esports should count as sports.","Competition and training make esports sports.","Sports should require substantial physical activity.","Explain a similarity to traditional sport.","Explain why physical activity is essential."),
 topic("pineapple","Rivet","Does pineapple belong on pizza?","Pineapple belongs on pizza.","Sweet pineapple improves some pizzas.","Pineapple does not belong on pizza.","Describe a flavor combination that works.","Explain why it clashes with pizza."),
 topic("pets","Pip","Are cats better pets than dogs?","Cats are better pets than dogs.","Cats fit more households.","Dogs are better companions for more people.","Give an example of a household suited to cats.","Give an example of what dogs do better."),
 topic("superpowers","Moss","Would teleportation be better than flight?","Teleportation is the better superpower.","Instant travel is more useful than flight.","Flight would be safer or more enjoyable.","Give a situation where teleportation wins.","Give a situation where flight wins."),
 topic("dessert","Rivet","Should dessert be eaten before dinner?","Dessert should sometimes come before dinner.","Reversing the order can make meals more fun.","Dinner should come before dessert.","Explain when dessert-first makes sense.","Explain why the usual order works."),
 topic("aliens","Pip","Should humans send messages into deep space?","Humans should actively message possible aliens.","Contact is worth attempting.","Humans should listen without broadcasting.","Explain a benefit of making contact.","Explain a risk of revealing our location."),
 topic("time_travel","Moss","Should time travel be used to change history?","People should use time travel to improve history.","Some past harms should be prevented.","History should never be deliberately changed.","Give an example and address side effects.","Explain why unintended effects are too risky."),
})
function Definitions.Score(text)return WritingChecklist.Evaluate(text)end
return Definitions
