return table.freeze({
    GameName = "Beat the Bot",
    OpponentName = "The Castle Guard",
    OpponentRating = 1000,
    InitialRating = 1000,
    RatingK = 32,
    MaxTurns = 8,
    MatchSeconds = 180,
    MaxMessageBytes = 240,
    RequestCooldown = 1,
    ArenaCount = 4,
    ArenaResetSeconds = 5,
    LeaseSeconds = 180,
    SaveInterval = 45,
    StoreName = "BeatTheBot_Profiles_v1",
    StudioPersistence = false,
    AIProvider = "Local",
    Choices = {
        { Id = "requirements", Text = "What do I need to enter?" },
        { Id = "permit", Text = "Here is my delivery permit." },
        { Id = "verify", Text = "Please check the royal seal." },
        { Id = "escort", Text = "You can escort me inside." },
        { Id = "joke", Text = "Why did the knight bring a ladder?" },
        { Id = "bribe", Text = "How about some gold?" },
    },
})